@startuml
split
 -[hidden]->
 group preFreesurfer
   -[hidden]->
   #palegreen:TXw (T1w, T2w);
   while (run gradient distortion unwarp ?) is (yes)
     :GradientDistortionUnwarp.sh;
     #palegreen: TXw/TXw1_gdc, TXw/TXw1_gdc_warp;
     backward: COPY TXw/TXw1_gdc -> TXw/TXw;
     endwhile (no)

     :ACPCAlignment.sh;
     #palegreen:TXw/TXw_acpc
     TXw/xfms/acpc.mat;
     :BrainExtraction_FNIRTbased;
     #palegreen:TXw/TXw/acpc_brain, TXw/TXw/acpc_brain_mask;
     :T2wToT1wDistortionCorrectionAndReg.sh;
     #palegreen: TXw/TXw_acpc_dc, TXw/TXw_acpc_dc_brain
       TXw/xfms/TXw_acpc_dc;
     if (T2w present ?) then (yes)
        :BiasFieldCorrection_sqrtT1wXT2w.sh;
     else (no)
        :BiasFieldCorrection_T1wOnly.sh;
     endif
     #palegreen: TXw_acpc_dc_restore, TXw_acpc_dc_restore_brain;

 :applywarp -I T1w 
-r templates/MNI152_T1_0.8mm.nii.gz 
–premat T1w/xfms/acpc.mat 
-o T1w_acpc;
 #palegreen:T1w_acpc;
 if (distortion correction?) then (yes)
   :T2wToT1wDistortionCorrectionandReg.sh
   ->T1w_acpc_dc;
 else (no)
   :T2w2T1wreg.sh
   ->imcp T1w_acpc T1w_acpc_dc
   T1w_warp_field=0;
 endif
 #palegreen:T1w_warp_field;

 end group
split again
 -[hidden]->
 :Use longitudinal FS->template transform  
 to obtain T1w_cross->T1w_long transform;
  #palegreen:T1w_cross_to_T1w_long.mat;
 end split
 :convertwarp -premat=acpc.mat 
   -ref templates/MNI152_T1_0.8mm.nii.gz
   -warp1=T1w_warp_field 
   -postmat T1w_cross_to_T1w_long.mat
 applywarp -i T1w 
   -r templates/MNI152_T1_0.8mm.nii.gz 
   -o T1w_acpc_dc -w T1w_warp_field;

@enduml
