@startuml
group PrePostFreesurferPipeline-long Gain Field Correction
split
    -[hidden]->
    split
        -[hidden]->
        #palegreen:$T1w_dir_long/$Timepoint_long
        /mri/brain.mgz;
    split again
        -[hidden]->
        #palegreen:$T1w_dir_long/xfms
        /norm_to_T1w_cross.lta;
    end split
    :mri_vol2vol;
    #orange:$T1w_dir_long
    /T1w_acpc_dc_brain;
split again
-[hidden]->
#palegreen:$T1w_dir_long
/T1w_acpc_dc;
end split
    if ( Use T2w ?) then (yes)
        #palegreen:$T1w_dir_long
        /T2w_acpc_dc;
        :BiasFieldCorrection_sqrtT1wXT2w.sh;
    
    else (no)        
        :BiasFieldCorrection_T1wOnly.sh;
    endif
    #orange:${T1w_dir_long}/BiasField_acpc_dc;
    :Take absolute value, 
    divide by the gain field;
    split
        #palegreen:$T1w_dir_long
        /T1w_acpc_dc,
        #palegreen:$T1w_dir_long
        /T2w_acpc_dc;
        :apply brain mask;
        if ( Use T2w ?) then (yes)
            #orange: $T1w_dir_long
            /T2w_acpc_dc_restore_brain;
        endif
        detach
        #orange:$T1w_dir_long
        /T1w_acpc_dc_restore_brain;
        detach 

    split again 
        #orange:$T1w_dir_long
        /$T1w_acpc_dc_restore;
        detach
    end split
end group
@enduml