@startuml
group prePostFreesurfer-long: resample T2w to acpc_dc space (template)
split
    -[hidden]->
    split
        -[hidden]->
        split
            -[hidden]->
            if (Readout distortion correction?) then (no)
            
                group No readout distortion correction
                    split    
                        -[hidden]->
                        :create_zero_warp 
                        $T2w_dir_long/xfms
                        /T2w_acpc_Warp.nii.gz;
                        #orange:$T2w_dir_long/xfms
                        /T2w_acpc_Warp.nii.gz;
                    split again
                        -[hidden]->
                        #palegreen:$T1w_dir_long/xfms
                        /T1w_cross_to_T1w_long.mat
                        $T2w_dir_cross/T2wToT1wReg
                        /T2w2T1w.mat;
                        :convert_xfm;
                        #orange:$T2w_dir_long/xfms
                        /T2w_acpc2Template.mat;
                    end split
                end group
            else (yes)
                group Readout distortion correction
                   split
                   -[hidden]->
                    #palegreen:$T1w_dir_long/xfms
                    /T1w_cross_to_T1w_long.mat
                    $T2w_dir_cross
                    /T2wToT1wDistortionCorrectAndReg
                    /T2w_reg.mat;
                    :convert_xfm;
                    #orange:$T2w_dir_long/xfms
                    /T2w_acpc2Template.mat;   
                    split again
                    -[hidden]->
                    #palegreen: $T2w_dir_cross 
                    /T2wToT1wDistortionCorrectAndReg
                    /T2w_acpc_Warp.nii.gz;
                    end split
                end group
            endif
        end split        
    split again
        -[hidden]->
        #palegreen:$T2w_dir_cross
        /xfms/acpc.mat;
    end split
    :convertwarp;
    #orange:$T2w_dir_long/xfms/T2w2template.nii.gz;
    split again
        -[hidden]->
        #palegreen:$T2w_dir_cross
        /T2w.nii.gz;
    end split
    :applywarp;
    #orange:$T1w_dir_long/T1w_acpc_dc.nii.gz;
end group

@enduml
