@startuml Template creation
group Resampling the template to T1w_acpc_dc space
split 
    -[hidden]->
    #palegreen:FS-long T1w template,
    FS-long T1w template brain;
split again 
    -[hidden]->
    #palegreen:FS-long T2w template,
    FS-long T2w template brain;
split again
    -[hidden]->
    #palegreen:Freesurfer->FSL
    resize/resample
    norm_to_T1w_cross.lta;
end split
    :mri_vol2vol;
if ( Use T2w ?) then (yes)
    #orange: $T1w_dir_template/T2w_acpc_dc_restore.nii.gz,
    $T1w_dir_template/T2w_acpc_dc_restore_brain.nii.gz;
endif
#orange: $T1w_dir_template/T1w_acpc_dc_restore.nii.gz,
$T1w_dir_template/T1w_acpc_dc_restore_brain.nii.gz;
end group
@enduml