EnvironmentScript="/media/myelin/brainmappers/Connectome_Project/MishaLongitudinal/hcp/scripts/SetUpHCPPipeline-long.sh"
source $EnvironmentScript 

Path=/media/myelin/brainmappers/Connectome_Project/MishaLongitudinal/hcp/functional_test.cross.10.23.2024
Session=HCA6002236_V1_MR
fMRIName=rfMRI_REST1_AP
fMRITimeSeries=${Path}/${Session}/unprocessed/$fMRIName/${Session}_${fMRIName}.nii.gz
fMRISBRef="${Path}/${Session}/unprocessed/${fMRIName}/${Session}_${fMRIName}_SBRef.nii.gz"
EchoSpacing="0.00058"
DistortionCorrection="TOPUP"
BiasCorrection="SEBASED"
SpinEchoPhaseEncodeNegative="$(find ${Path}/${Session}/unprocessed/${fMRIName} -name ${Session}_SpinEchoFieldMap[0-9]_AP.nii.gz)"
SpinEchoPhaseEncodePositive="$(find ${Path}/${Session}/unprocessed/${fMRIName} -name ${Session}_SpinEchoFieldMap[0-9]_PA.nii.gz)"
TopUpConfig="${HCPPIPEDIR_Config}/b02b0.cnf"
MagnitudeInputName="NONE"
PhaseInputName="NONE"
DeltaTE="NONE"
GEB0InputName="NONE"
FinalFMRIResolution="2"
GradientDistortionCoeffs="NONE"
MCType="MCFLIRT"
IsLongitudinal=1
LongitudinalSession=HCA6002236_V1_MR.long.HCA6002236_V1_V2_V3

T1wImage="T1w_acpc_dc"
T1wRestoreImage="T1w_acpc_dc_restore"
T1wRestoreImageBrain="T1w_acpc_dc_restore_brain"
T1wFolder="T1w" #Location of T1w images
AtlasSpaceFolder="MNINonLinear"
ResultsFolder="Results"
BiasField="BiasField_acpc_dc"
BiasFieldMNI="BiasField"
T1wAtlasName="T1w_restore"
MovementRegressor="Movement_Regressors" #No extension, .txt appended
MotionMatrixFolder="MotionMatrices"
MotionMatrixPrefix="MAT_"
FieldMapOutputName="FieldMap"
MagnitudeOutputName="Magnitude"
MagnitudeBrainOutputName="Magnitude_brain"
ScoutName="Scout"
OrigScoutName="${ScoutName}_orig"
OrigTCSName="${NameOffMRI}_orig"
FreeSurferBrainMask="brainmask_fs"
fMRI2strOutputTransform="${NameOffMRI}2str"
RegOutput="Scout2T1w"
AtlasTransform="acpc_dc2standard"
OutputfMRI2StandardTransform="${NameOffMRI}2standard"
Standard2OutputfMRITransform="standard2${NameOffMRI}"
QAImage="T1wMulEPI"
JacobianOut="Jacobian"
SessionFolder="$Path"/"$Session"
SessionFolderLong="$Path"/"$LongitudinalSession"