#!/bin/sh
#LD_LIBRARY_PATH=$PWD/../libs_linux64 ../exe_linux64/wb_import $@


#
# Point to the actual application executable
#
directory=`dirname $0`

if [ -z $LD_LIBRARY_PATH ]; then
export LD_LIBRARY_PATH=$directory/../libs_linux64
else
export LD_LIBRARY_PATH=$directory/../libs_linux64:$LD_LIBRARY_PATH
fi

echo $LD_LIBRARY_PATH

$directory/../exe_linux64/wb_import $*

