; Values only set once
warp_res_init           = 32
warp_scaling            = 1 1 2 2 2 2 2
img_warp_space          = {{Reference1}}
lambda_reg              = 4.0e5 3.7e-1 3.1e-1 2.6e-1 2.2e-1 1.8e-1 1.5e-1
hires                   = 3.9
optimiser_max_it_lowres = 5
optimiser_max_it_hires  = 5

; First scalar pair
img_ref_scalar      = {{Reference1}}
img_mov_scalar      = {{T1wRestore}}
aff_ref_scalar      = {{HCPPIPEDIR}}/MMORF/scripts/identity.mat
aff_mov_scalar      = {{wd}}/xfms/acpc2MMORFLinear.mat
use_implicit_mask   = 0
use_mask_ref_scalar = 1 1 1 1 1 1 1
use_mask_mov_scalar = 0 0 0 0 0 0 0
mask_ref_scalar     = {{ReferenceMask}}
mask_mov_scalar     = {{brainmaskedited}}
fwhm_ref_scalar     = 8.0 8.0 4.0 2.0 1.0 0.5 0.25
fwhm_mov_scalar     = 8.0 8.0 4.0 2.0 1.0 0.5 0.25
lambda_scalar       = 1 1 1 1 1 1 1
estimate_bias       = 1
bias_res_init       = 16
lambda_bias_reg     = 1e9 1e9 1e9 1e9 1e9 1e9 1e9

; Second scalar pair
img_ref_scalar      = {{Reference2}}
img_mov_scalar      = {{T2wRestore}}
aff_ref_scalar      = {{HCPPIPEDIR}}/MMORF/scripts/identity.mat
aff_mov_scalar      = {{wd}}/xfms/acpc2MMORFLinear.mat
use_implicit_mask   = 0
use_mask_ref_scalar = 1 1 1 1 1 1 1
use_mask_mov_scalar = 0 0 0 0 0 0 0
mask_ref_scalar     = {{ReferenceMask}}
mask_mov_scalar     = {{brainmaskedited}}
fwhm_ref_scalar     = 8.0 8.0 4.0 2.0 1.0 0.5 0.25
fwhm_mov_scalar     = 8.0 8.0 4.0 2.0 1.0 0.5 0.25
lambda_scalar       = 1 1 1 1 1 1 1
estimate_bias       = 1
bias_res_init       = 16
lambda_bias_reg     = 1e9 1e9 1e9 1e9 1e9 1e9 1e9

; First tensor pair
img_ref_tensor      = {{DTIref}}
img_mov_tensor      = {{DTI}}
aff_ref_tensor      = {{HCPPIPEDIR}}/MMORF/scripts/identity.mat
aff_mov_tensor      = {{wd}}/xfms/acpc2MMORFLinear.mat
use_mask_ref_tensor = 1 1 1 1 1 1 1
use_mask_mov_tensor = 1 1 1 1 1 1 1
mask_ref_tensor     = {{DTIrefMask}}
mask_mov_tensor     = {{DTImask}}
fwhm_ref_tensor     = 8.0 8.0 4.0 2.0 1.0 0.5 0.25
fwhm_mov_tensor     = 8.0 8.0 4.0 2.0 1.0 0.5 0.25
lambda_tensor       = 1 1 1 1 1 1 1

; Output warp
warp_out        = {{wd}}/xfms/mov_to_ref_mm_warp
jac_det_out     = {{wd}}/xfms/mov_to_ref_mm_jac
bias_out        = {{wd}}/xfms/mov_to_ref_mm_bias