#!/bin/bash

#   hcp_fix_multi_run - wrapper script for FIX, for HCP pipelines to clean multiple fMRI runs at a time (useful for cleaning shorter runs)
#
#   Requires FIX version 1.067 or later and FSL 6.0 melodic version
#
#   Stephen Smith and Matthew F. Glasser
#
#   SHCOPYRIGHT
#
#   Changes by Timothy B. Brown <tbbrown@wustl.edu>
#
#   1) Changes to support 7T ICAFIX processing based on changes originally made by Keith Jamison <kjamison@umn.edu>
#   2) Changes to log output messages to aid in debugging 
#
#   Changes by Tim Coalson
#
#   1) use melodic from $PATH by default, to make it easier to replace the default version FSL ships with
#
#   Changes by Takuya Hayashi
#
#   1) use brain mask in melodic to reduce memory usage (helps get around bad default compilation operations)
#
#   Changes by Michael Harms
#
#   1) Improvements to script readability 

set -e

DEBUG="TRUE"
g_script_name=$(basename "${0}")

log_Debug() {
	local msg="$*"
	local date_time=$(date)
	local output_msg
	if [ "${DEBUG}" = "TRUE" ]; then
		output_msg="${date_time} - ${g_script_name} - DEBUG - ${msg}"
		echo "${output_msg}"
		>&2 echo "${output_msg}"
	fi
}

log_Inform() {
	local msg="$*"
	local date_time=$(date)
	local output_msg
	output_msg="${date_time} - ${g_script_name} - INFORM - ${msg}"
	echo "${output_msg}"
	>&2 echo "${output_msg}"
}

log_Error() {
	local msg="$*"
	local date_time=$(date)
	local output_msg
	output_msg="${date_time} - ${g_script_name} - ERROR - ${msg}"
	echo ${output_msg}
	>&2 echo "${output_msg}"
}

this_script_dir=$(readlink -f "$(dirname "$0")")

# Set this before calling hcp_fix instead, to make it more flexible
#FSL_FIXDIR=$( cd $(dirname $0) ; pwd)
#export FSL_FIXDIR
log_Inform "FSL_FIXDIR: ${FSL_FIXDIR}"

# All fix settings are held in the settings.sh file - edit this file to suit your setup
source ${FSL_FIXDIR}/settings.sh

#############################################################

Usage() {
    cat <<EOF

hcp_fix_multi_run <4D_FMRI_data> <highpass> <concat_name> <do_motion_regression> [<TrainingFile>]
  <highpass> is the temporal highpass full-width (2*sigma) to use, in seconds
  <do_motion_regression> must be specified, use TRUE or FALSE

e.g.   hcp_fix_multi_run BOLD_REST1_RL/BOLD_REST1_RL.nii.gz@BOLD_REST1_RL/BOLD_REST1_RL.nii.gz 200 BOLD_REST1_RL_LR/BOLD_REST1_RL_LR.nii.gz TRUE

for detrending-like behaviour, set <highpass> to 2000
use 0 to do only a linear detrend

EOF
    exit 1
}

if (( $# < 4 ))
then
    #Usage does an exit
    Usage
fi

unset POSIXLY_CORRECT

demeanMovementRegressors() {
	In=${1}
	log_Debug "demeanMovementRegressors: In: ${In}"
	Out=${2}
	log_Debug "demeanMovementRegressors: Out: ${Out}"
	log_Debug "demeanMovementRegressors: getting nCols"
	nCols=$(head -1 ${In} | wc -w)
	
	log_Debug "demeanMovementRegressors: nCols: ${nCols}"
	log_Debug "demeanMovementRegressors: getting nRows"
	nRows=$(wc -l < ${In})
	log_Debug "demeanMovementRegressors: nRows: ${nRows}"
	
	AllOut=""
	c=1
	while (( c <= nCols )) ; do
		ColIn=`cat ${In} | sed 's/  */ /g' | sed 's/^ //g' | cut -d " " -f ${c}`
		bcstring=$(echo "$ColIn" | tr '\n' '+' | sed 's/\+*$//g')
		valsum=$(echo "$bcstring" | bc -l)
		valmean=$(echo "$valsum / $nRows" | bc -l)
		ColOut=""
		r=1
		while (( r <= nRows )) ; do
			val=`echo "${ColIn}" | head -${r} | tail -1`
			newval=`echo "${val} - ${valmean}" | bc -l`
			ColOut=`echo ${ColOut} $(printf "%10.6f" $newval)`
			r=$((r+1))
		done
		ColOut=`echo ${ColOut} | tr ' ' '\n'`
		AllOut=`paste <(echo "${AllOut}") <(echo "${ColOut}")`
		c=$((c+1))
	done
	echo "${AllOut}" > ${Out}
}

hp=$2
if [[ $(echo "${hp} < 0" | bc) == "1" ]]
then
    log_Error "highpass value must not be negative"
    exit 1
fi
log_Inform "hp: ${hp}"

unset TrainingData
if [ $# -ge 5 ] ; then
TrainingData=$5
fi

fmris=`echo ${1} | sed 's/@/ /g'` # replaces the @ that combines the filenames with ' '
log_Inform "fmris: ${fmris}"
ConcatName="${3}"
log_Inform "ConcatName: ${ConcatName}"

#this case logic could go in a helper function, interpret_as_bool or something
case $(echo "$4" | tr '[:upper:]' '[:lower:]') in
    ( true | yes )
        doMotionRegression=TRUE
        ;;
    ( false | no | none )
        doMotionRegression=FALSE
        ;;
    ( * )
        log_Error "'$4' is not valid for <do_motion_regression>, please use TRUE or FALSE"
        exit 1
        ;;
esac

DIR=`pwd`

echo $fmris | tr ' ' '\n' #separates paths separated by ' '

#Loops over the runs and do highpass on each of them
log_Inform "Looping over files and doing highpass to each of them"

NIFTIvolMergeSTRING=""
NIFTIvolhpVNMergeSTRING=""
SBRefVolSTRING=""
MeanVolSTRING=""
VNVolSTRING=""
CIFTIMergeSTRING=""
CIFTIhpVNMergeSTRING=""
MeanCIFTISTRING=""
VNCIFTISTRING=""
MovementNIFTIMergeSTRING=""
MovementNIFTIhpMergeSTRING=""
MovementTXTMergeSTRING=""

for fmri in $fmris ; do
	log_Inform "Top of loop through fmris: fmri: ${fmri}"

	fmriNoExt=$($FSLDIR/bin/remove_ext $fmri)

	# Create necessary strings for merging across runs
	NIFTIvolMergeSTRING+="${fmriNoExt}_demean "
	NIFTIvolhpVNMergeSTRING+="${fmriNoExt}_hp${hp}_vnts "  #These are the individual run, VN'ed *time series*
	SBRefVolSTRING+="${fmriNoExt}_SBRef "
	MeanVolSTRING+="${fmriNoExt}_mean "
	VNVolSTRING+="${fmriNoExt}_vn "  #These are the individual run, VN'ed *maps*
	CIFTIMergeSTRING+="-cifti ${fmriNoExt}_Atlas_demean.dtseries.nii "
	CIFTIhpVNMergeSTRING+="-cifti ${fmriNoExt}_Atlas_hp${hp}_vn.dtseries.nii "
	MeanCIFTISTRING+="-cifti ${fmriNoExt}_Atlas_mean.dscalar.nii "
	VNCIFTISTRING+="-cifti ${fmriNoExt}_Atlas_vn.dscalar.nii "
	MovementNIFTIMergeSTRING+="${fmriNoExt}_hp${hp}.ica/mc/prefiltered_func_data_mcf_conf.nii.gz "
	MovementNIFTIhpMergeSTRING+="${fmriNoExt}_hp${hp}.ica/mc/prefiltered_func_data_mcf_conf_hp.nii.gz "
	
	cd `dirname $fmri`
	log_Debug "pwd: "$(pwd)
	fmri=`basename $fmri`
	# Note: After the following 'imglob' command, $fmri will no longer have an extension
	fmri=`$FSLDIR/bin/imglob $fmri`
	[ `imtest $fmri` != 1 ] && echo No valid 4D_FMRI input file specified && exit 1
	fmri_orig=$fmri

	mkdir -p ${fmri}_hp$hp.ica/mc
	if [ -f Movement_Regressors.txt ] ; then
		log_Debug "About to create ${fmri}_hp${hp}.ica/mc/prefiltered_func_data_mcf.par file"
		cat Movement_Regressors.txt | awk '{ print $4 " " $5 " " $6 " " $1 " " $2 " " $3}' > ${fmri}_hp${hp}.ica/mc/prefiltered_func_data_mcf.par
	else
		log_Error "Movement_Regressors.txt not retrieved properly." 
		exit -1
	fi

	tr=`$FSLDIR/bin/fslval $fmri pixdim4` 
	log_Inform "tr: $tr"
	log_Inform "processing FMRI file $fmri with highpass $hp"

	#Demean movement regressors, volumes, and CIFTI data
	demeanMovementRegressors Movement_Regressors.txt Movement_Regressors_demean.txt
	MovementTXTMergeSTRING+="$(pwd)/Movement_Regressors_demean.txt "

	${FSLDIR}/bin/fslmaths $fmri -Tmean ${fmri}_mean
	${FSLDIR}/bin/fslmaths $fmri -sub ${fmri}_mean ${fmri}_demean

	${FSL_FIX_WBC} -cifti-reduce ${fmri}_Atlas.dtseries.nii MEAN ${fmri}_Atlas_mean.dscalar.nii
	${FSL_FIX_WBC} -cifti-math "TCS - MEAN" ${fmri}_Atlas_demean.dtseries.nii -var TCS ${fmri}_Atlas.dtseries.nii -var MEAN ${fmri}_Atlas_mean.dscalar.nii -select 1 1 -repeat
	
	if [ -e .fix.functionhighpassandvariancenormalize.log ] ; then
		rm .fix.functionhighpassandvariancenormalize.log
	fi
	${FSL_FIXDIR}/call_matlab.sh -l .fix.functionhighpassandvariancenormalize.log -r "addpath('${this_script_dir}'); functionhighpassandvariancenormalize($tr, $hp, '$fmri', '${FSL_FIX_WBC}');"
	
	log_Inform "Dims: $(cat ${fmri}_dims.txt)"

	# ADD COMMENT: Why are the following 3 lines necessary?
	fslmaths $(pwd)/${fmri}_hp${hp}.ica/mc/prefiltered_func_data_mcf_conf.nii.gz -Tmean $(pwd)/${fmri}_hp${hp}.ica/mc/prefiltered_func_data_mcf_conf_mean.nii.gz
	fslmaths $(pwd)/${fmri}_hp${hp}.ica/mc/prefiltered_func_data_mcf_conf.nii.gz -sub $(pwd)/${fmri}_hp${hp}.ica/mc/prefiltered_func_data_mcf_conf_mean.nii.gz $(pwd)/${fmri}_hp${hp}.ica/mc/prefiltered_func_data_mcf_conf.nii.gz
	$FSLDIR/bin/imrm $(pwd)/${fmri}_hp${hp}.ica/mc/prefiltered_func_data_mcf_conf_mean.nii.gz

	# Rename $fmri to include the hp string
	fmri=${fmri}_hp$hp
	#cd ${fmri}.ica
	# Per https://github.com/Washington-University/Pipelines/issues/60, the following line doesn't appear to be necessary
	#$FSLDIR/bin/imln ../$fmri filtered_func_data
	#cd ..
	log_Inform "Bottom of loop through fmris: fmri: ${fmri}"
done

AlreadyHP="-1" #Don't run highpass on concatenated data

#Make Concatenated Folder
ConcatFolder=`dirname ${ConcatName}`
log_Inform "Making concatenated folder: ${ConcatFolder}"
if [ ! -e ${ConcatFolder} ] ; then  
	mkdir ${ConcatFolder} 
else
	rm -r ${ConcatFolder}  
	mkdir ${ConcatFolder}
fi

ConcatNameNoExt=$($FSLDIR/bin/remove_ext $ConcatName)

# Merge volumes from the individual runs
fslmerge -tr ${ConcatNameNoExt}_demean ${NIFTIvolMergeSTRING} $tr
fslmerge -tr ${ConcatNameNoExt}_hp${hp}_vnts ${NIFTIvolhpVNMergeSTRING} $tr
fslmerge -t  ${ConcatNameNoExt}_SBRef ${SBRefVolSTRING}
fslmerge -t  ${ConcatNameNoExt}_mean ${MeanVolSTRING}
fslmerge -t  ${ConcatNameNoExt}_vn ${VNVolSTRING}
# Average across runs
fslmaths ${ConcatNameNoExt}_SBRef -Tmean ${ConcatNameNoExt}_SBRef
fslmaths ${ConcatNameNoExt}_mean -Tmean ${ConcatNameNoExt}_mean
fslmaths ${ConcatNameNoExt}_vn -Tmean ${ConcatNameNoExt}_vn  # Mean VN map across the individual runs
fslmaths ${ConcatNameNoExt}_hp${hp}_vnts -mul ${ConcatNameNoExt}_vn ${ConcatNameNoExt}_hp${hp}
  # Preceeding line restores the mean VN map; The resulting TCS becomes the input to a 2nd pass of VN, which then becomes the input to melodic
fslmaths ${ConcatNameNoExt}_demean -add ${ConcatNameNoExt}_mean ${ConcatNameNoExt}
# Same thing for the CIFTI
${FSL_FIX_WBC} -cifti-merge ${ConcatNameNoExt}_Atlas_demean.dtseries.nii ${CIFTIMergeSTRING}
${FSL_FIX_WBC} -cifti-average ${ConcatNameNoExt}_Atlas_mean.dscalar.nii ${MeanCIFTISTRING}
${FSL_FIX_WBC} -cifti-average ${ConcatNameNoExt}_Atlas_vn.dscalar.nii ${VNCIFTISTRING}
${FSL_FIX_WBC} -cifti-math "TCS + MEAN" ${ConcatNameNoExt}_Atlas.dtseries.nii -var TCS ${ConcatNameNoExt}_Atlas_demean.dtseries.nii -var MEAN ${ConcatNameNoExt}_Atlas_mean.dscalar.nii -select 1 1 -repeat
${FSL_FIX_WBC} -cifti-merge ${ConcatNameNoExt}_Atlas_hp${hp}_vn.dtseries.nii ${CIFTIhpVNMergeSTRING}
${FSL_FIX_WBC} -cifti-math "TCS * VN" ${ConcatNameNoExt}_Atlas_hp${hp}.dtseries.nii -var TCS ${ConcatNameNoExt}_Atlas_hp${hp}_vn.dtseries.nii -var VN ${ConcatNameNoExt}_Atlas_vn.dscalar.nii -select 1 1 -repeat
fslmaths ${ConcatNameNoExt}_SBRef -bin ${ConcatNameNoExt}_brain_mask # Inserted to create mask to be used in melodic for suppressing memory error - Takuya Hayashi

# Disambiguate the "1st level" vn map created above (as mean of the individual run VN maps)
# from the VN map that will be output from running fix on the concatenated runs
$FSLDIR/bin/immv ${ConcatNameNoExt}_hp${hp}_vnts ${ConcatNameNoExt}_hp${hp}_vnts0

cd ${ConcatFolder}

# concatfmri is intensity normalized and has no overall mean.
# It is also not variance normalized (the mean VN map *across runs* was "restored" above).
# But is detrended and within run demeaned and variance normalized for both volume and CIFTI
concatfmri=`basename ${ConcatNameNoExt}`_hp${hp}
concat_fmri_orig=`basename ${ConcatNameNoExt}`

mkdir -p ${concatfmri}.ica
log_Debug "About to put contents of ${MovementTXTMergeSTRING} in Movement_Regressors_demean.txt file"
cat ${MovementTXTMergeSTRING} > Movement_Regressors_demean.txt
mkdir ${concatfmri}.ica/mc
fslmerge -tr ${concatfmri}.ica/mc/prefiltered_func_data_mcf_conf_hp ${MovementNIFTIhpMergeSTRING} $tr
fslmerge -tr ${concatfmri}.ica/mc/prefiltered_func_data_mcf_conf ${MovementNIFTIMergeSTRING} $tr


log_Inform "running MELODIC"
log_Debug "About to run melodic: Contents of ${concatfmri}.ica follow"
if [ "${DEBUG}" = "TRUE" ] ; then
	ls -lRa ${concatfmri}.ica
fi

#grab melodic from $PATH by default, don't hardcode it with respect to $FSLDIR
#we need to do "if which ..." because the script currently uses set -e
if which melodic &> /dev/null
then
    MELODIC=$(which melodic 2> /dev/null)
else
    #if it isn't even in $PATH, fall back on FSLDIR
    MELODIC="${FSLDIR}/bin/melodic"
fi

log_Inform "Running melodic located at: $MELODIC"
log_Debug "Beginning of melodic version log, help, and checksum"
if [ "${DEBUG}" = "TRUE" ] ; then
	log_Debug "$MELODIC --version"
	$MELODIC --version
	log_Debug "$MELODIC --help"
	$MELODIC --help
	log_Debug "md5sum $MELODIC"
	md5sum $MELODIC
fi
log_Debug "End of melodic version log, help, and checksum"

###Run on concatenated file --

${FSL_FIXDIR}/call_matlab.sh -l .fix.functionhighpassandvariancenormalize.log -r "addpath('${this_script_dir}'); functionhighpassandvariancenormalize($tr, $AlreadyHP, '$concatfmri', '${FSL_FIX_WBC}');"
Dim=`cat ${concatfmri}_dims.txt`

log_Inform "Dim: ${Dim}"

## Run melodic on concatenated file
# Use the Wishart-based dim estimate instead of the melodic-based estimate (--dim=${Dim})
# Also turn off melodic VN and feed in the input that has already been VN'ed instead (--vn flag, which turns OFF melodic's vn)
# Added "-m ${ConcatNameNoExt}_brain_mask" to avoid memory issue - Takuya Hayahsi July 2018
melodic_cmd="${MELODIC} -i ${concatfmri}_vnts -o ${concatfmri}.ica/filtered_func_data.ica --nobet --report --Oall --tr=$tr --vn --dim=${Dim} -m ${ConcatNameNoExt}_brain_mask"
if [ "${DEBUG}" = "TRUE" ] ; then
	melodic_cmd="${melodic_cmd} --verbose --debug"
fi

log_Inform "melodic_cmd: ${melodic_cmd}"
${melodic_cmd}
return_code=$?
log_Inform "melodic has been run: return_code = ${return_code}"
log_Debug "melodic has been run: Contents of ${concatfmri}.ica follow"
if [ "${DEBUG}" = "TRUE" ] ; then
	ls -lRa ${concatfmri}.ica
fi

if [ "${return_code}" -ne "0" ] ; then
    log_Error "melodic has returned a non-zero code"
	log_Error "Exiting this script with -1 return value."
	exit -1
fi

cd ${concatfmri}.ica

$FSLDIR/bin/imln ../$concatfmri filtered_func_data
$FSLDIR/bin/imln filtered_func_data.ica/mask mask

if [ `$FSLDIR/bin/imtest ../${concat_fmri_orig}_SBRef` = 1 ] ; then
	$FSLDIR/bin/imln ../${concat_fmri_orig}_SBRef mean_func
else
	$FSLDIR/bin/imln filtered_func_data.ica/mean mean_func
fi

if [ -f ../${concat_fmri_orig}_Atlas_hp${hp}.dtseries.nii ] ; then
	$FSLDIR/bin/imln ../${concat_fmri_orig}_Atlas_hp${hp}.dtseries.nii Atlas.dtseries.nii
fi

mkdir -p reg
cd reg

i_am_at=`pwd`
log_Debug "current folder ${i_am_at}"

$FSLDIR/bin/imln ../../../../T1w_restore_brain highres
$FSLDIR/bin/imln ../../../../wmparc wmparc
$FSLDIR/bin/imln ../mean_func example_func
$FSLDIR/bin/makerot --theta=0 > highres2example_func.mat
if [ `$FSLDIR/bin/imtest ../../../../T2w` = 1 ] ; then
	$FSLDIR/bin/fslmaths ../../../../T1w -div ../../../../T2w veins -odt float
	$FSLDIR/bin/flirt -in ../../../../brainmask_fs.nii.gz -ref veins -out veinbrainmask -applyxfm
	$FSLDIR/bin/fslmaths veinbrainmask -bin veinbrainmask
	$FSLDIR/bin/fslmaths veins -div `$FSLDIR/bin/fslstats veins -k veinbrainmask -P 50` -mul 2.18 -thr 10 -min 50 -div 50 veins
	$FSLDIR/bin/flirt -in veins -ref example_func -applyxfm -init highres2example_func.mat -out veins_exf
	$FSLDIR/bin/fslmaths veins_exf -mas example_func veins_exf
fi
cd ../..

log_Inform "running FIX"

# Changes to handle user specified training data file
if [ "X${TrainingData}" != X ]; then
	# User has specified a training data file
	
	# add .RData suffix if not already there
	if [[ "${TrainingData}" != *.RData ]]; then 
		TrainingData=${TrainingData}.RData
	fi
	
	# if the specified TrainingData is not a full path to an existing file,
	# assume that the user is specifying the name of a file in the training_files folder in FSL_FIXDIR
	if [ ! -f "${TrainingData}" ]; then 
		TrainingData=${FSL_FIXDIR}/training_files/${TrainingData}
	fi
	log_Inform "User has specified a training data file: ${TrainingData}"
	
	# finally, if the TrainingData file is not found, report an error and get out of here
	if [ ! -f "${TrainingData}" ]; then
		log_Error "FIX training data not found: ${TrainingData}"
		exit -1
	fi
	
	# now run fix
	if [[ ${doMotionRegression} == "TRUE" ]]
	then
	    #use array for whitespace safety, even if the rest of the script isn't
    	fix_cmd=("${FSL_FIXDIR}/fix" "${concatfmri}.ica" "${TrainingData}" 10 -m -h "${AlreadyHP}")
	else
        #-h is actually a subargument to -m, and will cause problems if specified without (or even not directly following) -m
    	fix_cmd=("${FSL_FIXDIR}/fix" "${concatfmri}.ica" "${TrainingData}" 10)
	fi
	log_Inform "fix_cmd: ${fix_cmd[*]}"
	"${fix_cmd[@]}"
	return_code=$?
	log_Inform "return_code from fix_cmd: ${return_code}"
	if [ "${return_code}" -ne "0" ]; then
		exit ${return_code}
	fi
	
else
	# user has not specified a training data file
	#TSC: so, let's look for it and give a useful error, rather than pretending they didn't want to do what they said
	#TSC: if you WANT to use, say, hp150 with hp2000 training, it should be explicitly requested by the user
	#TSC: exception: we will recommend hp 0 (linear) for performance, and hp 2000 is already trained, and largely indistinguishable
	log_Inform "User has NOT specified a training data file"
	training_hp="${hp}"
	if [[ ! -f "${FSL_FIXDIR}/training_files/HCP_hp${hp}.RData" ]]
	then
	    if (( hp == 0 ))
	    then
	        #hack: hp 2000 is close enough to a linear detrend only, but linear detrend is far faster
	        #we know the hp 2000 training data exists, so use it if we don't see a hp 0 set
	        training_hp=2000
	    else
    	    log_Error "no standard training data found for specified high pass (${hp}), please specify training data manually or use a standard high pass setting"
    	    exit 1
	    fi
	fi
	log_Inform "using training data ${FSL_FIXDIR}/training_files/HCP_hp${training_hp}.RData"
	if [[ ${doMotionRegression} == "TRUE" ]]
	then
        fix_cmd=("${FSL_FIXDIR}/fix" "${concatfmri}.ica" "${FSL_FIXDIR}/training_files/HCP_hp${training_hp}.RData" 10 -m -h "${AlreadyHP}")
    else
        #-h is actually a subargument to -m, and will cause problems if specified without (or even not directly following) -m
        fix_cmd=("${FSL_FIXDIR}/fix" "${concatfmri}.ica" "${FSL_FIXDIR}/training_files/HCP_hp${training_hp}.RData" 10)
    fi
	log_Inform "fix_cmd: ${fix_cmd[*]}"
	"${fix_cmd[@]}"
	return_code=$?
	log_Inform "return_code from fix_cmd: ${return_code}"
	if [ "${return_code}" -ne "0" ]; then
		exit ${return_code}
	fi
fi

log_Inform "Done running FIX"

log_Debug "Moving ${concatfmri}.ica/filtered_func_data_clean to ${concatfmri}_clean"
$FSLDIR/bin/immv ${concatfmri}.ica/filtered_func_data_clean ${concatfmri}_clean
$FSLDIR/bin/immv ${concatfmri}.ica/filtered_func_data_clean_vn ${concatfmri}_clean_vn

log_Debug "Checking for existence of ${concatfmri}.ica/Atlas_clean.dtseries.nii"
if [ -f ${concatfmri}.ica/Atlas_clean.dtseries.nii ] ; then
	log_Debug "Moving ${concatfmri}.ica to ${concat_fmri_orig}_Atlas_hp${hp}_clean.dtseries.nii"
	/bin/mv ${concatfmri}.ica/Atlas_clean.dtseries.nii ${concat_fmri_orig}_Atlas_hp${hp}_clean.dtseries.nii
	/bin/mv ${concatfmri}.ica/Atlas_clean_vn.dscalar.nii ${concat_fmri_orig}_Atlas_hp${hp}_clean_vn.dscalar.nii
fi

#Cleaned volume and CIFTI have no mean and are intensity normalized by multiplying in the overall variance normalization
#This must be divided back out and the original variance normalization multipled back in
#Then the mean is added back in to return the timeseries to its original state minus the noise

Start="1"
for fmri in $fmris ; do
	fmriNoExt=$($FSLDIR/bin/remove_ext $fmri)
	NumTPS=`${FSL_FIX_WBC} -file-information ${fmriNoExt}_Atlas.dtseries.nii -no-map-info -only-number-of-maps`
	Stop=`echo "${NumTPS} + ${Start} -1" | bc -l`
	log_Inform "Start=${Start} Stop=${Stop}"
	
	log_Debug "cifti merging"
	cifti_out=${fmriNoExt}_Atlas_hp${hp}_clean.dtseries.nii
	${FSL_FIX_WBC} -cifti-merge ${cifti_out} -cifti ${concat_fmri_orig}_Atlas_hp${hp}_clean.dtseries.nii -column ${Start} -up-to ${Stop}
	${FSL_FIX_WBC} -cifti-math "((TCS / VNA) * VN) + Mean" ${fmriNoExt}_Atlas_hp${hp}_clean.dtseries.nii -var TCS ${fmriNoExt}_Atlas_hp${hp}_clean.dtseries.nii -var VNA `remove_ext ${concat_fmri_orig}`_Atlas_vn.dscalar.nii -select 1 1 -repeat -var VN ${fmriNoExt}_Atlas_vn.dscalar.nii -select 1 1 -repeat -var Mean ${fmriNoExt}_Atlas_mean.dscalar.nii -select 1 1 -repeat

	readme_for_cifti_out=${cifti_out%.dtseries.nii}.README.txt
	touch ${readme_for_cifti_out}
	short_cifti_out=${cifti_out##*/}
	echo "${short_cifti_out} was generated by applying \"multi-run FIX\" (using 'hcp_fix_multi_run')" >> ${readme_for_cifti_out}
	echo "across the following individual runs:" >> ${readme_for_cifti_out}
	for readme_fmri in ${fmris} ; do
		echo "  ${readme_fmri}" >> ${readme_for_cifti_out}
	done
		
	log_Debug "volume merging"
	${FSL_FIX_WBC} -volume-merge ${fmriNoExt}_hp${hp}_clean.nii.gz -volume ${concatfmri}_clean.nii.gz -subvolume ${Start} -up-to ${Stop}
	fslmaths ${fmriNoExt}_hp${hp}_clean.nii.gz -div `remove_ext ${concat_fmri_orig}`_vn -mul ${fmriNoExt}_vn -add ${fmriNoExt}_mean ${fmriNoExt}_hp${hp}_clean.nii.gz
	Start=`echo "${Start} + ${NumTPS}" | bc -l`
done


cd ${DIR}

