#!/bin/bash

#   hcp_fix - wrapper script for FIX, for HCP pipelines
#
#   Original by Stephen Smith, FMRIB Analysis Group
#
#   Copyright (C) 2012-2013 University of Oxford
#
#   SHCOPYRIGHT
#
#   Changes relative to the version of hcp_fix supplied by the FIX distribution:
#    (Tim Coalson, Tim Brown, Keith Jamison, Michael Harms)
#
#   1) Add a flag to to control whether motion regression is applied
#      (and appropriate conditional code based on that choice)
#   2) Defaults to using whatever version of 'melodic' is primary in $PATH,
#      rather than the $FSLDIR/bin version.
#   3) Remove the restriction on melodic to an upper-limit of 250 dimensions (no more "-d -250")
#   4) Add flexibility for user to specify their own training date file
#   5) Replaces the brainmask used as part of deriving the 'veins' image from one
#      derived from $FSL_FIXDIR/mask_files/hcp_0.7mm_brain_mask to the subject's
#      specific T1w/brainmask_fs.nii.gz
#   6) Includes more verbose output 

#############################################################

# Verify HCPPIPEDIR environment variable is set
if [ -z "${HCPPIPEDIR}" ]; then
	script_name=$(basename "${0}")
	echo "${script_name}: ABORTING: HCPPIPEDIR environment variable must be set"
	exit 1
fi

#  Load function libraries
source ${HCPPIPEDIR}/global/scripts/log.shlib # Logging related functions
log_Msg "HCPPIPEDIR: ${HCPPIPEDIR}"

log_debugOn="" # Set to any non-empty string (e.g., "true") to turn on debugging related output
               # Set to empty string to disable debugging related output

# Set this before calling hcp_fix instead, to make it more flexible
#FSL_FIXDIR=$( cd $(dirname $0) ; pwd)
#export FSL_FIXDIR
log_Msg "FSL_FIXDIR: ${FSL_FIXDIR}"

# All fix settings are held in the settings.sh file - edit this file to suit your setup
. ${FSL_FIXDIR}/settings.sh

#############################################################

Usage() {
    cat <<EOF

hcp_fix <4D_FMRI_data> <highpass> <do_motion_regression> [<TrainingFile>] [<FixThreshold>]

  Apply FIX cleaning to a single file

  <4D_FMRI_data>: fMRI run to be processed (nifti extension optional)

  <highpass>: 
     If > 0, is the temporal highpass full-width (2*sigma), in seconds, to apply using 'fslmaths -bptf'

     For detrending-like behaviour, set <highpass> to 2000

  <do_motion_regression>:
     Controls whether to regress motion parameters as part of the cleaning.
     Must be specified, use TRUE or FALSE

  [<TrainingFile>] (optional)
     Defaults to "HCP_hp${hp}.RData"

  [<FixThreshold>] (optional)
     Threshold setting in FIX that controls the sensitivity/specificity tradeoff.
     Default = 10.
     To specify a threshold, <TrainingFile> becomes a mandatory argument.

e.g.  hcp_fix rfMRI_REST1_RL/rfMRI_REST1_RL.nii.gz 2000 TRUE
        (if launching the script from the '\${StudyFolder}/\${Subject}/MNINonLinear/Results' directory)

EOF
    exit 1
}

if (( $# < 3 ))
then
    #Usage does an exit
    Usage
fi

fmri=$1
cd `dirname $fmri`
fmri=`basename $fmri`  # After this, $fmri no longer includes the leading directory components
fmri=`$FSLDIR/bin/imglob $fmri`  # After this, $fmri will no longer have an extension (if there was one initially)
[ `imtest $fmri` != 1 ] && echo No valid 4D_FMRI input file specified && exit 1

hp=$2

#this case logic could go in a helper function, interpret_as_bool or something
case $(echo "$3" | tr '[:upper:]' '[:lower:]') in
    ( true | yes )
        doMotionRegression=TRUE
        ;;
    ( false | no | none )
        doMotionRegression=FALSE
        ;;
    ( * )
        log_Err_Abort "error: '$3' is not valid for <do_motion_regression>, please use TRUE or FALSE"
        ;;
esac

unset TrainingData
unset FixThresh
if [ $# -ge 4 ] ; then
	TrainingData=$4
	FixThresh=$5
fi
if [ -z "${FixThresh}" ]; then
	FixThresh=10
fi

tr=`$FSLDIR/bin/fslval $fmri pixdim4`

log_Msg "processing FMRI file $fmri with highpass $hp"

if (( hp > 0 )) ; then
  log_Msg "running highpass"
  #convert to sigma in volumes (not seconds)
  hptr=$(echo "scale = 10; $hp / (2 * $tr)" | bc -l)
  ${FSLDIR}/bin/fslmaths $fmri -bptf $hptr -1 ${fmri}_hp$hp
  fmrihp=${fmri}_hp$hp
fi

log_Msg "running MELODIC"
mkdir -p ${fmrihp}.ica
log_Debug_Msg "About to run melodic: Contents of ${fmrihp}.ica follow"
if [ ! -z "${log_debugOn}" ] ; then
	ls -lRa ${fmrihp}.ica
fi

#grab melodic from $PATH by default, don't hardcode it with respect to $FSLDIR
#we need to do "if which ..." because the script currently uses set -e
if which melodic &> /dev/null
then
    MELODIC=$(which melodic 2> /dev/null)
else
    #if it isn't even in $PATH, fall back on FSLDIR
    MELODIC="${FSLDIR}/bin/melodic"
fi
log_Debug_Msg "Beginning of melodic version log"
if [ ! -z "${log_debugOn}" ] ; then
	"${MELODIC}" --version
fi
log_Debug_Msg "End of melodic version log"

${MELODIC} -i $fmrihp -o ${fmrihp}.ica/filtered_func_data.ica --nobet --report --Oall --tr=$tr
return_code=$?
log_Debug_Msg "melodic has been run: return_code = ${return_code}"
log_Debug_Msg "melodic has been run: Contents of ${fmrihp}.ica follow"
if [ ! -z "${log_debugOn}" ] ; then
	ls -lRa ${fmrihp}.ica
fi

if [ "${return_code}" -ne "0" ] ; then
    log_Err_Abort "melodic has returned a non-zero code"
fi

# Delete some time series, resulting from the '--Oall' option in melodic, that aren't needed
# (these may only get created in the context of MIGP)
$FSLDIR/bin/imrm ${fmrihp}.ica/filtered_func_data.ica/alldat
$FSLDIR/bin/imrm ${fmrihp}.ica/filtered_func_data.ica/concat_data

cd ${fmrihp}.ica

$FSLDIR/bin/imln ../$fmrihp filtered_func_data
$FSLDIR/bin/imln filtered_func_data.ica/mask mask

if [ `$FSLDIR/bin/imtest ../${fmri}_SBRef` = 1 ] ; then
  $FSLDIR/bin/imln ../${fmri}_SBRef mean_func
else
  $FSLDIR/bin/imln filtered_func_data.ica/mean mean_func
fi

if [ -f ../${fmri}_Atlas.dtseries.nii ] ; then
  $FSLDIR/bin/imln ../${fmri}_Atlas.dtseries.nii Atlas.dtseries.nii
fi

mkdir -p mc
if [ -f ../Movement_Regressors.txt ] ; then
  cat ../Movement_Regressors.txt | awk '{ print $4 " " $5 " " $6 " " $1 " " $2 " " $3}' > mc/prefiltered_func_data_mcf.par
else
  log_Err_Abort "Movement_Regressors.txt not retrieved properly." 
fi 

log_Msg "functionmotionconfounds log file is to be named: .fix.functionmotionconfounds.log instead of .fix.log"
#${FSL_FIXDIR}/call_matlab.sh -l .fix.log -f functionmotionconfounds $tr $hp 
${FSL_FIXDIR}/call_matlab.sh -l .fix.functionmotionconfounds.log -f functionmotionconfounds $tr $hp 

mkdir -p reg
cd reg

i_am_at=`pwd`
log_Debug_Msg "current folder ${i_am_at}"

$FSLDIR/bin/imln ../../../../T1w_restore_brain highres
$FSLDIR/bin/imln ../../../../wmparc wmparc
$FSLDIR/bin/imln ../mean_func example_func
$FSLDIR/bin/makerot --theta=0 > highres2example_func.mat
if [ `$FSLDIR/bin/imtest ../../../../T2w` = 1 ] ; then
  $FSLDIR/bin/fslmaths ../../../../T1w -div ../../../../T2w veins -odt float
  $FSLDIR/bin/fslmaths veins -div `$FSLDIR/bin/fslstats veins -k ../../../../brainmask_fs.nii.gz -P 50` -mul 2.18 -thr 10 -min 50 -div 50 veins
  $FSLDIR/bin/flirt -in veins -ref example_func -applyxfm -init highres2example_func.mat -out veins_exf
  $FSLDIR/bin/fslmaths veins_exf -mas example_func veins_exf
fi
cd ../..

log_Msg "running FIX"

# Changes to handle user specified training data file
if [ "X${TrainingData}" != X ]; then  # User has specified a training data file
	
	# add .RData suffix if not already there
	if [[ "${TrainingData}" != *.RData ]]; then 
		TrainingData=${TrainingData}.RData
	fi

	# if the specified TrainingData is not a full path to an existing file,
	# assume that the user is specifying the name of a file in the training_files folder in FSL_FIXDIR
	if [ ! -f "${TrainingData}" ]; then 
		TrainingData=${FSL_FIXDIR}/training_files/${TrainingData}
	fi

	# finally, if the TrainingData file is not found, report an error and get out of here
	if [ ! -f "${TrainingData}" ]; then
		log_Err_Abort "FIX training data not found: ${TrainingData}"
	fi

	# now run fix
	if [[ ${doMotionRegression} == "TRUE" ]]; then
	    #use array for whitespace safety, even if the rest of the script isn't
	    fix_cmd=("${FSL_FIXDIR}/fix" "${fmrihp}.ica" "${TrainingData}" "${FixThresh}" -m -h "${hp}")
	else
		#-h is actually a subargument to -m, and will cause problems if specified without (or even not directly following) -m
	    fix_cmd=("${FSL_FIXDIR}/fix" "${fmrihp}.ica" "${TrainingData}" "${FixThresh}")
	fi
	log_Msg "About to run: ${fix_cmd[*]}"
	"${fix_cmd[@]}"

else
	# user has not specified a training data file
	#TSC: so, let's look for it and give a useful error, rather than pretending they didn't want to do what they said
	#TSC: if you WANT to use, say, hp150 with hp2000 training, it should be explicitly requested by the user
	if [[ ! -f "${FSL_FIXDIR}/training_files/HCP_hp${hp}.RData" ]]; then
		#currently, hp 0 doesn't do detrend in hcp_fix, so we can't use the same logic as in hcp_fix_multi_run
		log_Err_Abort "no standard training data found for specified high pass (${hp}), please specify training data manually or use a standard high pass setting"
	fi
	log_Msg "using training data ${FSL_FIXDIR}/training_files/HCP_hp${hp}.RData"
	if [[ ${doMotionRegression} == "TRUE" ]]; then
	    fix_cmd=("${FSL_FIXDIR}/fix" "${fmrihp}.ica" "${FSL_FIXDIR}/training_files/HCP_hp${hp}.RData" "${FixThresh}" -m -h "${hp}")
    else
        #-h is actually a subargument to -m, and will cause problems if specified without (or even not directly following) -m
	    fix_cmd=("${FSL_FIXDIR}/fix" "${fmrihp}.ica" "${FSL_FIXDIR}/training_files/HCP_hp${hp}.RData" "${FixThresh}")
    fi
    log_Msg "About to run: ${fix_cmd[*]}"
    "${fix_cmd[@]}"
fi

$FSLDIR/bin/immv ${fmrihp}.ica/filtered_func_data_clean ${fmrihp}_clean

if [ -f ${fmrihp}.ica/Atlas_clean.dtseries.nii ] ; then
  /bin/mv ${fmrihp}.ica/Atlas_clean.dtseries.nii ${fmri}_Atlas_hp${hp}_clean.dtseries.nii
fi

# The variance normalization ("_vn") outputs of fix (fix_3_clean) require use of fix1.067 or later
# So check whether those files exist before moving/renaming them
if [ `$FSLDIR/bin/imtest ${fmrihp}.ica/filtered_func_data_clean_vn` = 1 ] ; then
	$FSLDIR/bin/immv ${fmrihp}.ica/filtered_func_data_clean_vn ${fmrihp}_clean_vn
fi
if [ -f ${fmrihp}.ica/Atlas_clean_vn.dscalar.nii ] ; then
	/bin/mv ${fmrihp}.ica/Atlas_clean_vn.dscalar.nii ${fmri}_Atlas_hp${hp}_clean_vn.dscalar.nii
fi
