#!/bin/bash

#   hcp_fix_multi_run - wrapper script for FIX, for HCP pipelines to clean multiple fMRI runs at a time (useful for cleaning shorter runs)
#
#   Requires FIX version 1.065 or later and FSL 6.0 melodic version
#
#   Stephen Smith and Matthew F. Glasser
#
#   SHCOPYRIGHT
#
#   Changes by Timothy B. Brown <tbbrown@wustl.edu>
#
#   1) Changes to support 7T ICAFIX processing based on changes originally made by Keith Jamison <kjamison@umn.edu>
#   2) Changes to log output messages to aid in debugging 
#

DEBUG="TRUE"
g_script_name=$(basename "${0}")

log_Debug() {
	local msg="${1}"
	local date_time=$(date)
	local output_msg
	if [ "${DEBUG}" = "TRUE" ]; then
		output_msg="${date_time} - ${g_script_name} - DEBUG - ${msg}"
		echo "${output_msg}"
		>&2 echo "${output_msg}"
	fi
}

log_Inform() {
	local msg="${1}"
	local date_time=$(date)
	local output_msg
	output_msg="${date_time} - ${g_script_name} - INFORM - ${msg}"
	echo "${output_msg}"
	>&2 echo "${output_msg}"
}

log_Error() {
	local msg="${1}"
	local date_time=$(date)
	local output_msg
	output_msg="${date_time} - ${g_script_name} - ERROR - ${msg}"
	echo ${output_msg}
	>&2 echo "${output_msg}"
}

# Set this before calling hcp_fix instead, to make it more flexible
#FSL_FIXDIR=$( cd $(dirname $0) ; pwd)
#export FSL_FIXDIR
log_Inform "FSL_FIXDIR: ${FSL_FIXDIR}"

# All fix settings are held in the settings.sh file - edit this file to suit your setup
source ${FSL_FIXDIR}/settings.sh

#############################################################

Usage() {
    cat <<EOF

hcp_fix <4D_FMRI_data> <highpass> <concat_name> [<TrainingFile>]
  with <highpass> being the temporal highpass full-width (2*sigma) in seconds

e.g.   hcp_fix BOLD_REST1_RL/BOLD_REST1_RL.nii.gz 200

for detrending-like behaviour, set <highpass> to 2000

EOF
    exit 1
}

[ "$2" = "" ] && Usage

unset POSIXLY_CORRECT

demeanMovementRegressors() {
	In=${1}
	log_Debug "demeanMovementRegressors: In: ${In}"
	Out=${2}
	log_Debug "demeanMovementRegressors: Out: ${Out}"
	log_Debug "demeanMovementRegressors: getting nCols"
	nCols=$(head -1 ${In} | wc -w)
	
	log_Debug "demeanMovementRegressors: nCols: ${nCols}"
	log_Debug "demeanMovementRegressors: getting nRows"
	nRows=$(wc -l < ${In})
	log_Debug "demeanMovementRegressors: nRows: ${nRows}"
	
	AllOut=""
	c=1
	while [ ${c} -le ${nCols} ] ; do
		ColIn=`cat ${In} | sed 's/  / /g' | sed 's/  / /g' | sed 's/^ //g'| cut -d " " -f ${c}`
		valsum=0
		r=1
		while [ ${r} -le ${nRows} ] ; do
			val=`echo "${ColIn}" | head -${r} | tail -1`
			valsum=`echo ${valsum} + ${val} | bc -l`
			r=$((${r}+1))
		done
		valmean=`echo ${valsum} / ${r} | bc -l`
		ColOut=""
		r=1
		while [ ${r} -le ${nRows} ] ; do
			val=`echo "${ColIn}" | head -${r} | tail -1`
			newval=`echo "${val} - ${valmean}" | bc -l`
			ColOut=`echo ${ColOut} $(printf "%10.6f" $newval)`
			r=$((${r}+1))
		done
		ColOut=`echo ${ColOut} | tr ' ' '\n'`
		AllOut=`paste <(echo "${AllOut}") <(echo "${ColOut}")` #Figure out how to do this paste
		c=$((${c}+1))
	done
	echo "${AllOut}" > ${Out}
}

hp=$2
log_Inform "hp: ${hp}"

unset TrainingData
if [ $# -ge 4 ] ; then
TrainingData=$4
fi

fmris=`echo ${1} | sed 's/@/ /g'` # replaces the @ that combines the filenames with ' '
log_Inform "fmris: ${fmris}"
ConcatName="${3}"
log_Inform "ConcatName: ${ConcatName}"

DIR=`pwd`

echo $fmris | tr ' ' '\n' #separates paths separated by ' '

#Loops over the files and does highpass to each of them
log_Inform "Looping over files and doing highpass to each of them"

NIFTIvolMergeSTRING=""
NIFTIvolhpMergeSTRING=""
CIFTIMergeSTRING=""
CIFTIhpMergeSTRING=""
MovementTXTMergeSTRING=""
MovementNIFTIMergeSTRING=""
MovementNIFTIhpMergeSTRING=""
SBRefVolSTRING=""
MeanVolSTRING=""
MeanCIFTISTRING=""
for fmri in $fmris ; do  
	log_Inform "Top of loop through fmris: fmri: ${fmri}"
	NIFTIvolMergeSTRING=`echo "${NIFTIvolMergeSTRING}$($FSLDIR/bin/remove_ext $fmri)_demean "`
	NIFTIvolhpMergeSTRING=`echo "${NIFTIvolhpMergeSTRING}$($FSLDIR/bin/remove_ext $fmri)_hp$hp "`
	SBRefVolSTRING=`echo "${SBRefVolSTRING}$($FSLDIR/bin/remove_ext $fmri)_SBRef "`
	MeanVolSTRING=`echo "${MeanVolSTRING}$($FSLDIR/bin/remove_ext $fmri)_mean "`
	CIFTIMergeSTRING=`echo "${CIFTIMergeSTRING} -cifti $($FSLDIR/bin/remove_ext $fmri)_Atlas_demean.dtseries.nii"`
	CIFTIhpMergeSTRING=`echo "${CIFTIhpMergeSTRING} -cifti $($FSLDIR/bin/remove_ext $fmri)_Atlas_hp$hp.dtseries.nii"`
	MeanCIFTISTRING=`echo "${MeanCIFTISTRING} -cifti $($FSLDIR/bin/remove_ext $fmri)_Atlas_mean.dscalar.nii "`
	cd `dirname $fmri`
	log_Debug "pwd: "$(pwd)
	fmri=`basename $fmri`
	fmri=`$FSLDIR/bin/imglob $fmri`
	[ `imtest $fmri` != 1 ] && echo No valid 4D_FMRI input file specified && exit 1
	fmri_orig=$fmri


	tr=`$FSLDIR/bin/fslval $fmri pixdim4` 
	log_Inform "tr: $tr"
	log_Inform "processing FMRI file $fmri with highpass $hp"

	${FSLDIR}/bin/fslmaths $fmri -Tmean ${fmri}_mean
	${FSLDIR}/bin/fslmaths $fmri -sub ${fmri}_mean ${fmri}_demean
	
	if [ $hp -gt 0 ] ; then 
		log_Inform "running highpass"
		hptr=`echo "10 k $hp 2 / $tr / p" | dc -` 
		log_Inform "hptr $hptr"
		${FSLDIR}/bin/fslmaths $fmri -sub ${fmri}_mean -bptf $hptr -1 ${fmri}_hp$hp 
	fi
	
	demeanMovementRegressors Movement_Regressors.txt Movement_Regressors_demean.txt
	MovementTXTMergeSTRING=`echo "${MovementTXTMergeSTRING}$(pwd)/Movement_Regressors_demean.txt "`
	
	mkdir -p ${fmri}_hp$hp.ica/mc
	if [ -f Movement_Regressors.txt ] ; then
		log_Debug "About to create ${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf.par file"
		cat Movement_Regressors.txt | awk '{ print $4 " " $5 " " $6 " " $1 " " $2 " " $3}' > ${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf.par
	else
		log_Error "Movement_Regressors.txt not retrieved properly." 
		exit -1
	fi
	MovementNIFTIMergeSTRING=`echo "${MovementNIFTIMergeSTRING}$(pwd)/${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf_conf.nii.gz "`
	MovementNIFTIhpMergeSTRING=`echo "${MovementNIFTIhpMergeSTRING}$(pwd)/${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf_conf_hp.nii.gz "`

	log_Inform "functionmotionconfounds log file is to be named: .fix.functionmotionconfounds.log instead of .fix.log"
	cd ${fmri}_hp$hp.ica
	${FSL_FIXDIR}/call_matlab.sh -l .fix.functionmotionconfounds.log -f functionmotionconfounds $tr $hp 
	cd ..
	
	fslmaths $(pwd)/${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf_conf.nii.gz -Tmean $(pwd)/${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf_conf_mean.nii.gz
	fslmaths $(pwd)/${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf_conf.nii.gz -sub $(pwd)/${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf_conf_mean.nii.gz $(pwd)/${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf_conf.nii.gz
	$FSLDIR/bin/imrm $(pwd)/${fmri}_hp$hp.ica/mc/prefiltered_func_data_mcf_conf_mean.nii.gz
	
	${FSL_FIX_WBC} -cifti-reduce $($FSLDIR/bin/remove_ext $fmri)_Atlas.dtseries.nii MEAN $($FSLDIR/bin/remove_ext $fmri)_Atlas_mean.dscalar.nii
	${FSL_FIX_WBC} -cifti-math "TCS - MEAN" $($FSLDIR/bin/remove_ext $fmri)_Atlas_demean.dtseries.nii -var TCS $($FSLDIR/bin/remove_ext $fmri)_Atlas.dtseries.nii -var MEAN $($FSLDIR/bin/remove_ext $fmri)_Atlas_mean.dscalar.nii -select 1 1 -repeat
	
	${FSL_FIX_WBC} -cifti-convert -to-nifti ${fmri}_Atlas.dtseries.nii ${fmri}_Atlas_FAKENIFTI.nii.gz
	${FSLDIR}/bin/fslmaths ${fmri}_Atlas_FAKENIFTI.nii.gz -bptf $hptr -1 ${fmri}_Atlas_hp${hp}_FAKENIFTI.nii.gz
	${FSL_FIX_WBC} -cifti-convert -from-nifti ${fmri}_Atlas_hp${hp}_FAKENIFTI.nii.gz ${fmri}_Atlas.dtseries.nii ${fmri}_Atlas_hp$hp.dtseries.nii
	$FSLDIR/bin/imrm ${fmri}_Atlas_FAKENIFTI ${fmri}_Atlas_hp${hp}_FAKENIFTI
	fmri=${fmri}_hp$hp
	cd ${fmri}.ica
	# Per https://github.com/Washington-University/Pipelines/issues/60, the following line doesn't appear to be necessary
	#$FSLDIR/bin/imln ../$fmri filtered_func_data
	cd ..
	log_Inform "Bottom of loop through fmris: fmri: ${fmri}"
done

AlreadyHP="-1" #Don't run highpass on concatenated data

#Make Concatenated Folder
ConcatFolder=`dirname ${ConcatName}`
log_Inform "Making concatenated folder: ${ConcatFolder}"
if [ ! -e ${ConcatFolder} ] ; then  
	mkdir ${ConcatFolder} 
else
	rm -r ${ConcatFolder}  
	mkdir ${ConcatFolder}
fi


fslmerge -tr `remove_ext ${ConcatName}`_demean ${NIFTIvolMergeSTRING} $tr
fslmerge -tr `remove_ext ${ConcatName}`_hp$hp ${NIFTIvolhpMergeSTRING} $tr
fslmerge -t  `remove_ext ${ConcatName}`_SBRef ${SBRefVolSTRING}
fslmerge -t  `remove_ext ${ConcatName}`_mean ${MeanVolSTRING}
fslmaths `remove_ext ${ConcatName}`_SBRef -Tmean `remove_ext ${ConcatName}`_SBRef
fslmaths `remove_ext ${ConcatName}`_mean -Tmean `remove_ext ${ConcatName}`_mean
fslmaths `remove_ext ${ConcatName}`_hp$hp -add `remove_ext ${ConcatName}`_mean `remove_ext ${ConcatName}`_hp$hp 
fslmaths `remove_ext ${ConcatName}`_demean -add `remove_ext ${ConcatName}`_mean `remove_ext ${ConcatName}` 
$FSLDIR/bin/imrm `remove_ext ${ConcatName}`_mean
${FSL_FIX_WBC} -cifti-merge `remove_ext ${ConcatName}`_Atlas_demean.dtseries.nii ${CIFTIMergeSTRING}
${FSL_FIX_WBC} -cifti-average `remove_ext ${ConcatName}`_Atlas_mean.dscalar.nii ${MeanCIFTISTRING}
${FSL_FIX_WBC} -cifti-math "TCS + MEAN" `remove_ext ${ConcatName}`_Atlas.dtseries.nii -var TCS `remove_ext ${ConcatName}`_Atlas_demean.dtseries.nii -var MEAN `remove_ext ${ConcatName}`_Atlas_mean.dscalar.nii -select 1 1 -repeat
${FSL_FIX_WBC} -cifti-merge `remove_ext ${ConcatName}`_Atlas_hp$hp.dtseries.nii ${CIFTIhpMergeSTRING}
cd ${ConcatFolder}

concatfmri=`basename $(remove_ext ${ConcatName})`_hp$hp
concat_fmri_orig=`basename $(remove_ext ${ConcatName})`

mkdir -p ${concatfmri}.ica
log_Debug "About to put contents of ${MovementTXTMergeSTRING} in Movement_Regressors_demean.txt file"
cat ${MovementTXTMergeSTRING} > Movement_Regressors_demean.txt
mkdir ${concatfmri}.ica/mc
fslmerge -tr ${concatfmri}.ica/mc/prefiltered_func_data_mcf_conf_hp ${MovementNIFTIhpMergeSTRING} $tr
fslmerge -tr ${concatfmri}.ica/mc/prefiltered_func_data_mcf_conf ${MovementNIFTIMergeSTRING} $tr

log_Inform "running MELODIC"
log_Debug "About to run melodic: Contents of ${concatfmri}.ica follow"
if [ "${DEBUG}" = "TRUE" ] ; then
	ls -lRa `remove_ext ${concatfmri}`.ica
fi

log_Inform "Running melodic located at: ${FSLDIR}/bin/melodic"
log_Debug "Beginning of melodic version log, help, and checksum"
if [ "${DEBUG}" = "TRUE" ] ; then
	log_Debug "${FSLDIR}/bin/melodic --version"
	${FSLDIR}/bin/melodic --version
	log_Debug "${FSLDIR}/bin/melodic --help"
	${FSLDIR}/bin/melodic --help
	log_Debug "md5sum ${FSLDIR}/bin/melodic"
	md5sum ${FSLDIR}/bin/melodic
fi
log_Debug "End of melodic version log, help, and checksum"

###Run on concatenated file --

# Original melodic command without logging of command
# ${FSLDIR}/bin/melodic -i $concatfmri -o ${concatfmri}.ica/filtered_func_data.ica -d -250 --nobet --report --Oall --tr=$tr
#
# melodic command with verbose output and debugging output, used when trying to determine why melodic was crashing
# melodic_cmd="${FSLDIR}/bin/melodic -i $concatfmri -o ${concatfmri}.ica/filtered_func_data.ica --nobet --report --Oall --tr=$tr --verbose --debug"

melodic_cmd="${FSLDIR}/bin/melodic -i $concatfmri -o ${concatfmri}.ica/filtered_func_data.ica --nobet --report --Oall --tr=$tr"
log_Inform "melodic_cmd: ${melodic_cmd}"
${melodic_cmd}
return_code=$?
log_Inform "melodic has been run: return_code = ${return_code}"
log_Debug "melodic has been run: Contents of ${concatfmri}.ica follow"
if [ "${DEBUG}" = "TRUE" ] ; then
	ls -lRa `remove_ext ${concatfmri}`.ica
fi

if [ "${return_code}" -ne "0" ] ; then
    log_Error "melodic has returned a non-zero code"
	log_Error "Exiting this script with -1 return value."
	exit -1
fi

cd `remove_ext ${concatfmri}`.ica

$FSLDIR/bin/imln ../$concatfmri filtered_func_data
$FSLDIR/bin/imln filtered_func_data.ica/mask mask

if [ `$FSLDIR/bin/imtest ../${concat_fmri_orig}_SBRef` = 1 ] ; then
	$FSLDIR/bin/imln ../${concat_fmri_orig}_SBRef mean_func
else
	$FSLDIR/bin/imln filtered_func_data.ica/mean mean_func
fi

if [ -f ../${concat_fmri_orig}_Atlas_hp$hp.dtseries.nii ] ; then
	$FSLDIR/bin/imln ../${concat_fmri_orig}_Atlas_hp$hp.dtseries.nii Atlas.dtseries.nii
fi

mkdir -p reg
cd reg

i_am_at=`pwd`
log_Debug "current folder ${i_am_at}"

$FSLDIR/bin/imln ../../../../T1w_restore_brain highres
$FSLDIR/bin/imln ../../../../wmparc wmparc
$FSLDIR/bin/imln ../mean_func example_func
$FSLDIR/bin/makerot --theta=0 > highres2example_func.mat
if [ `$FSLDIR/bin/imtest ../../../../T2w` = 1 ] ; then
	$FSLDIR/bin/fslmaths ../../../../T1w -div ../../../../T2w veins -odt float
	$FSLDIR/bin/flirt -in ${FSL_FIXDIR}/mask_files/hcp_0.7mm_brain_mask -ref veins -out veinbrainmask -applyxfm
	$FSLDIR/bin/fslmaths veinbrainmask -bin veinbrainmask
	$FSLDIR/bin/fslmaths veins -div `$FSLDIR/bin/fslstats veins -k veinbrainmask -P 50` -mul 2.18 -thr 10 -min 50 -div 50 veins
	$FSLDIR/bin/flirt -in veins -ref example_func -applyxfm -init highres2example_func.mat -out veins_exf
	$FSLDIR/bin/fslmaths veins_exf -mas example_func veins_exf
fi
cd ../..

log_Inform "running FIX"

# Changes to handle user specified training data file
if [ "X${TrainingData}" != X ]; then
	# User has specified a training data file
	
	# add .RData suffix if not already there
	if [[ "${TrainingData}" != *.RData ]]; then 
		TrainingData=${TrainingData}.RData
	fi
	
	# if the specified TrainingData is not a full path to an existing file,
	# assume that the user is specifying the name of a file in the training_files folder in FSL_FIXDIR
	if [ ! -f "${TrainingData}" ]; then 
		TrainingData=${FSL_FIXDIR}/training_files/${TrainingData}
	fi
	log_Inform "User has specified a training data file: ${TrainingData}"
	
	# finally, if the TrainingData file is not found, report an error and get out of here
	if [ ! -f "${TrainingData}" ]; then
		log_Error "FIX training data not found: ${TrainingData}"
		exit -1
	fi
	
	# now run fix
	fix_cmd="${FSL_FIXDIR}/fix ${concatfmri}.ica ${TrainingData} 10 -m -h ${AlreadyHP}"
	log_Inform "fix_cmd: ${fix_cmd}"
	${fix_cmd}
	return_code=$?
	log_Inform "return_code from fix_cmd: ${return_code}"
	if [ "${return_code}" -ne "0" ]; then
		exit ${return_code}
	fi
	
else
	log_Inform "User has NOT specified a training data file"
	log_Inform "using training data ${FSL_FIXDIR}/training_files/HCP_hp2000.RData"
	${FSL_FIXDIR}/fix ${concatfmri}.ica ${FSL_FIXDIR}/training_files/HCP_hp2000.RData 10 -m -h ${AlreadyHP}
fi

log_Inform "Done running FIX"

log_Debug "Moving ${concatfmri}.ica/filtered_func_data_clean to ${concatfmri}_clean"
$FSLDIR/bin/immv ${concatfmri}.ica/filtered_func_data_clean ${concatfmri}_clean

log_Debug "Checking for existence of ${concatfmri}.ica/Atlas_clean.dtseries.nii"
if [ -f ${concatfmri}.ica/Atlas_clean.dtseries.nii ] ; then
	log_Debug "Moving ${concatfmri}.ica to ${concat_fmri_orig}_Atlas_hp${hp}_clean.dtseries.nii"
	/bin/mv ${concatfmri}.ica/Atlas_clean.dtseries.nii ${concat_fmri_orig}_Atlas_hp${hp}_clean.dtseries.nii
fi

Start="1"
for fmri in $fmris ; do
	NumTPS=`${FSL_FIX_WBC} -file-information $(remove_ext ${fmri})_Atlas.dtseries.nii -no-map-info -only-number-of-maps`
	Stop=`echo "${NumTPS} + ${Start} -1" | bc -l`
	log_Inform "Start=${Start} Stop=${Stop}"
	
	log_Debug "cifti merging"
	cifti_out=`remove_ext ${fmri}`_Atlas_hp${hp}_clean.dtseries.nii
	${FSL_FIX_WBC} -cifti-merge ${cifti_out} -cifti ${concat_fmri_orig}_Atlas_hp${hp}_clean.dtseries.nii -column ${Start} -up-to ${Stop}

	readme_for_cifti_out=${cifti_out%.dtseries.nii}.README.txt
	touch ${readme_for_cifti_out}
	short_cifti_out=${cifti_out##*/}
	echo "${short_cifti_out} was generated by applying \"multi-run FIX\" (using 'hcp_fix_multi_run')" >> ${readme_for_cifti_out}
	echo "across the following individual runs:" >> ${readme_for_cifti_out}
	for readme_fmri in ${fmris} ; do
		echo "  ${readme_fmri}" >> ${readme_for_cifti_out}
	done
	
	log_Debug "volume merging"
	${FSL_FIX_WBC} -volume-merge `remove_ext ${fmri}`_hp${hp}_clean.nii.gz -volume ${concatfmri}_clean.nii.gz -subvolume ${Start} -up-to ${Stop}
	fslmaths `remove_ext ${fmri}`_hp${hp}_clean.nii.gz -Tmean `remove_ext ${fmri}`_hp${hp}_clean_mean
	fslmaths `remove_ext ${fmri}`_hp${hp}_clean.nii.gz -sub `remove_ext ${fmri}`_hp${hp}_clean_mean `remove_ext ${fmri}`_hp${hp}_clean.nii.gz ###Remove the run average mean again if added above
	fslmaths `remove_ext ${fmri}`_hp${hp}_clean.nii.gz -add `remove_ext ${fmri}`_mean `remove_ext ${fmri}`_hp${hp}_clean.nii.gz
	rm `remove_ext ${fmri}`_mean.nii.gz `remove_ext ${fmri}`_hp${hp}_clean_mean.nii.gz
	${FSL_FIX_WBC} -cifti-math "TCS + Mean" `remove_ext ${fmri}`_Atlas_hp${hp}_clean.dtseries.nii -var TCS `remove_ext ${fmri}`_Atlas_hp${hp}_clean.dtseries.nii -var Mean `remove_ext ${fmri}`_Atlas_mean.dscalar.nii -select 1 1 -repeat
	rm `remove_ext ${fmri}`_Atlas_mean.dscalar.nii
	Start=`echo "${Start} + ${NumTPS}" | bc -l`
done


cd ${DIR}

