#!/bin/sh

#   hcp_fix - wrapper script for FIX, for HCP pipelines
#
#   Stephen Smith, FMRIB Analysis Group
#
#   Copyright (C) 2012-2013 University of Oxford
#
#   SHCOPYRIGHT

#Set this before calling hcp_fix instead, to make it more flexible
#FSL_FIXDIR=$( cd $(dirname $0) ; pwd)
#export FSL_FIXDIR

# All fix settings are held in the settings.sh file - edit this file to suit your setup
. ${FSL_FIXDIR}/settings.sh

#############################################################

Usage() {
    cat <<EOF
hcp_fix <4D_FMRI_data> <highpass> [<TrainingFile>]
  with <highpass> being the temporal highpass full-width (2*sigma) in seconds
e.g.   hcp_fix BOLD_REST1_RL/BOLD_REST1_RL.nii.gz 200
for detrending-like behaviour, set <highpass> to 2000
EOF
    exit 1
}

[ "$2" = "" ] && Usage

fmri=$1
cd `dirname $fmri`
fmri=`basename $fmri`
fmri=`$FSLDIR/bin/imglob $fmri`
[ `imtest $fmri` != 1 ] && echo No valid 4D_FMRI input file specified && exit 1
fmri_orig=$fmri

hp=$2

unset TrainingData
if [ $# -ge 3 ]; then
  TrainingData=$3
fi

tr=`$FSLDIR/bin/fslval $fmri pixdim4`

echo "processing FMRI file $fmri with highpass $hp"

if [ $hp -gt 0 ] ; then
  echo "running highpass"
  hptr=`echo "10 k $hp 2 / $tr / p" | dc -`
  ${FSLDIR}/bin/fslmaths $fmri -bptf $hptr -1 ${fmri}_hp$hp
  fmri=${fmri}_hp$hp
fi

echo "running MELODIC"
mkdir -p ${fmri}.ica
$FSLDIR/bin/melodic -i $fmri -o ${fmri}.ica/filtered_func_data.ica -d -250 --nobet --report --Oall --tr=$tr

cd ${fmri}.ica

$FSLDIR/bin/imln ../$fmri filtered_func_data
$FSLDIR/bin/imln filtered_func_data.ica/mask mask

if [ `$FSLDIR/bin/imtest ../${fmri_orig}_SBRef` = 1 ] ; then
  $FSLDIR/bin/imln ../${fmri_orig}_SBRef mean_func
else
  $FSLDIR/bin/imln filtered_func_data.ica/mean mean_func
fi

if [ -f ../${fmri_orig}_Atlas.dtseries.nii ] ; then
  $FSLDIR/bin/imln ../${fmri_orig}_Atlas.dtseries.nii Atlas.dtseries.nii
fi

mkdir -p mc
if [ -a ../Movement_Regressors.txt ] ; then
  cat ../Movement_Regressors.txt | awk '{ print $4 " " $5 " " $6 " " $1 " " $2 " " $3}' > mc/prefiltered_func_data_mcf.par
else
  echo "ERROR: Movement_Regressors.txt not retrieved properly." 
  exit -1
fi 

${FSL_FIXDIR}/call_matlab.sh -L .fix.log -f functionmotionconfounds $tr $hp 

mkdir -p reg
cd reg
$FSLDIR/bin/imln ../../../../T1w_restore_brain highres
$FSLDIR/bin/imln ../../../../wmparc wmparc
$FSLDIR/bin/imln ../mean_func example_func
$FSLDIR/bin/makerot --theta=0 > highres2example_func.mat
$FSLDIR/bin/fslmaths ../../../../T1w -div ../../../../T2w veins -odt float
$FSLDIR/bin/fslmaths veins -div `$FSLDIR/bin/fslstats veins -k ${FSL_FIXDIR}/mask_files/hcp_0.7mm_brain_mask -P 50` -mul 2.18 -thr 10 -min 50 -div 50 veins
$FSLDIR/bin/flirt -in veins -ref example_func -applyxfm -init highres2example_func.mat -out veins_exf
$FSLDIR/bin/fslmaths veins_exf -mas example_func veins_exf
cd ../..

echo "running FIX"
if [ "X${TrainingData}" != X ]; then
	if [[ "${TrainingData}" != *.RData ]]; then
		TrainingData=${TrainingData}.RData
	fi
	if [ ! -f "${TrainingData}" ]; then
		TrainingData=${FSL_FIXDIR}/training_files/${TrainingData}
	fi
	
	if [ ! -f "${TrainingData}" ]; then
	  echo "ERROR: FIX training data not found: ${TrainingData}" 
	  exit -1
	fi
	
	${FSL_FIXDIR}/fix ${fmri}.ica $TrainingData 10 -m -h $hp
else
	if [ $hp != 2000 ] ; then
	  ${FSL_FIXDIR}/fix ${fmri}.ica ${FSL_FIXDIR}/training_files/HCP_hp200.RData 10 -m -h 200
	else
	  ${FSL_FIXDIR}/fix ${fmri}.ica ${FSL_FIXDIR}/training_files/HCP_hp2000.RData 10 -m -h 2000
	fi
fi

$FSLDIR/bin/immv ${fmri}.ica/filtered_func_data_clean ${fmri}_clean

if [ -f ${fmri}.ica/Atlas_clean.dtseries.nii ] ; then
  /bin/mv ${fmri}.ica/Atlas_clean.dtseries.nii ${fmri_orig}_Atlas_hp${hp}_clean.dtseries.nii
fi
